version: '3.8'
services:
  postgresql:
    container_name: "postgres"
    image: postgres:15.2-alpine
    restart: on-failure
    ports:
      - '5432:5432'
    volumes:
      - "C:/space/docker-volumes/db/money-minder:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=money-minder
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=rootadmin